CREATE SCHEMA IF NOT EXISTS futures;
CREATE SCHEMA IF NOT EXISTS backtest;
CREATE SCHEMA IF NOT EXISTS shared;
CREATE SCHEMA IF NOT EXISTS mt5;
CREATE SCHEMA IF NOT EXISTS fx_top;
CREATE TABLE IF NOT EXISTS shared.calendar (date date PRIMARY KEY, is_holiday boolean DEFAULT false);
